### ISSUE TITLE
Runtime error with Flipper

### ISSUE THREAD

**Issue by zuccha** [idnow/de.idnow.ios#101] opened 2021-07-01 12:46 UTC
# Description

When setting up a project using [Flipper](https://fbflipper.com/) debugger and IDnowSDK, the app crashes at runtime with the following error at line 110 of `CertificateUtils.cpp`
```
Thread 10: EXC_BAD_ACCESS (code=1, address=0x300000000)
```

Flipper is the default debugger shipped with [React Native](https://reactnative.dev/), but can be used in native apps as well.

We created an example project showcasing the error and uploaded it on [this repo](https://github.com/welldsagl/flipper-idnowsdk-test).

## Setup

Create a new iOS swift project from XCode.

Add the following `Podfile` and run `pod install`
```ruby
project 'FlipperIDnowSDKTest.xcodeproj'

flipperkit_version = '0.95.1'

target 'FlipperIDnowSDKTest' do
  platform :ios, '10.0'

  pod 'FlipperKit', '~>' + flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutComponentKitSupport', '~>' + flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
  # ...unfortunately at this time that means you'll need to explicitly mark
  # transitive dependencies as being for debug build only as well:
  pod 'Flipper-DoubleConversion', :configuration => 'Debug'
  pod 'Flipper-Folly', :configuration => 'Debug'
  pod 'Flipper-Glog', :configuration => 'Debug'
  pod 'Flipper-PeerTalk', :configuration => 'Debug'
  pod 'CocoaLibEvent', :configuration => 'Debug'
  pod 'boost-for-react-native', :configuration => 'Debug'
  pod 'OpenSSL-Universal', :configuration => 'Debug'
  pod 'CocoaAsyncSocket', :configuration => 'Debug'
  # ...except, of course, those transitive dependencies that your
  # application itself depends, e.g.:
  pod 'ComponentKit', '~> 0.31'

  pod 'IDnowSDK', '~> 4.1.7'
end
```

The `Podfile` includes all dependencies needed by Flipper, plus the `IDnowSDK` library.

Then, modify your `AppDelegate` as follows
```swift
import UIKit
import FlipperKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    let client = FlipperClient.shared()
    let layoutDescriptorMapper = SKDescriptorMapper(defaults: ())
    FlipperKitLayoutComponentKitSupport.setUpWith(layoutDescriptorMapper)
    client?.add(FlipperKitLayoutPlugin(rootNode: application, with: layoutDescriptorMapper!))
    client?.start()
    return true
  }
}
```

For more info about setting up Flipper, check the [official documentation](https://fbflipper.com/docs/getting-started/ios-native).

## Steps to reproduce

Build and run the app with Flipper open, the crash should occur at startup.

## Notes

A few things you might need to know:
- We are using version 4.1.7 of `IDnowSDK` because we are not being able to install later versions with Cocoapods. Trying to install version 5.0.7 leads to the following error
  ```
  [!] The following Swift pods cannot yet be integrated as static libraries:

  The Swift pod `IDnowSDK` depends upon `Masonry`, `SocketRocket`, `libPhoneNumber-iOS`, `FLAnimatedImage`, and `AFNetworking`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
  ```
  By adding `use_modular_headers!` as suggested, we end up with this error
  ```
  [!] Using Swift static libraries with custom module maps is currently not supported. Please build `IDnowSDK` as a framework or remove the custom module map.
  ```
- We first noticed the issue when upgrading Flipper from version 0.69 to 0.70. From version 0.70 onwards the problem as always been present (without upgrading/downgrading `IDnowSDK`).
- React Native allows to setup a new project via command line with `npx react-native init <project name>`. The new project is  created using Flipper 0.75 by default, making it impossible to use `IDnowSDK`  with a fresh React Native project.

**Comment by aare-undo-idnow** [comment] 2021-12-20 10:37
No longer reproducible with Flipper. `0.95.1` Seems like this was an a native library conflict that has been conflict that has been fixed on their side. 

I was gonna test whether it was maybe fixed on our side with the new build system release, but didn't even need to upgrade. Feel free to re-open (or comment) if this is still happening with a later version.

In fact, may it have even been an issue with the debug build itself? All kinds of freaky stuff can happen when debug symbols are attached.

**Closed by aare-undo-idnow** 2021-12-20 10:37 UTC

**Comment by YahiaJabeur** [comment] 2022-01-03 15:31
I m facing this issue on react native 0.66.2, flipper desktop 0.127.0
Any idea what's the issue ?

**Comment by yedidyak** [comment] 2022-05-08 14:31
Getting this with RN 0.66.4, flipper 0.145.0 now. Did anyone find the root cause for this?
