### ISSUE TITLE
modalPresentationStyle is pageSheet on "video overview check screen"

### ISSUE THREAD

**Issue by geissLA** [idnow/de.idnow.ios#82] opened 2020-02-27 10:54 UTC
Hi there.

We got an issue concerning the layout of the "video overview check screen". 
See picture for reference:

![Simulator Screen Shot - iPhone 11 Pro - 2020-02-27 at 10 40 37](https://user-images.githubusercontent.com/40028517/75437905-47367700-5957-11ea-8980-31938006d50d.png)

Since iOS 13 came along this screen, unlike the others, opens in a modal like fashion. Most probably caused by a changed default value for modal presentations from fullscreen to pagesheet.
This allows an unwanted dismissal gesture by swiping down the page.
Therefore we tried to customize the "modalPresentationStyle" to "UIModalPresentationFullScreen" on your exposed IDnowSettings inside "RNIdnow.m".
This unfortunately only changes the behaviour of the screens AFTER the "video overview check screen" which are already displaying in fullscreen.

We know of these issues ( #63  and #73 ) and followed the advices given there, to no prevail.

Does anyone know about this issue and could guide us in the right direction?

In our mobile App we are using the react-native IDnow wrapper on version 0.0.8 alongside IDnowSDK on version 3.22.1 (updating to 4.1.1 did not solve the problem).

**Comment by geissLA** [comment] 2020-03-30 14:41
Update: react-native IDnow wrapper was updated to version 0.1.0 and idnow ios got bumped to version 4.1.1.
Issue still remains.
It seems like the "video overview check screen" cannot be configured with your exposed settings object of the IDnowViewController.
Any hints?

**Comment by andrejcesen** [comment] 2020-04-09 16:15
We're experiencing the same issue and it's essentially preventing us from using Xcode 11, which will very soon be mandatory to use.

The SDK stumbles when being used in the same manner as in Xcode 10, i.e. calling `startIdentificationFromViewController:withCompletionBlock:` with `UINavigationController` works as expected on Xcode 10 by pushing onto its controller onto the navigation stack, while on Xcode 11 this results in presenting its own `UIViewController` modally using `UIModalPresentationAutomatic`. This results in the presentation above, being able to swipe it down, but this somehow breaks the SDK and it cannot be initiated again.

@idnow Please make this a priority, as this SDK will become unusable when Xcode 11 becomes mandatory.

**Comment by pavel-antonov-idnow** [comment] 2020-05-13 10:15
The issue is combined with #86  
Fix will follow soon.

**Comment by pavel-antonov-idnow** [comment] 2020-05-26 09:39
resolved with 4.1.7 release

**Closed** 2022-03-07 13:26 UTC
